// Copyright 2018 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "agones.dev/agones/pkg/apis/stable/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFleetAutoScalers implements FleetAutoScalerInterface
type FakeFleetAutoScalers struct {
	Fake *FakeStableV1alpha1
	ns   string
}

var fleetautoscalersResource = schema.GroupVersionResource{Group: "stable.agones.dev", Version: "v1alpha1", Resource: "fleetautoscalers"}

var fleetautoscalersKind = schema.GroupVersionKind{Group: "stable.agones.dev", Version: "v1alpha1", Kind: "FleetAutoScaler"}

// Get takes name of the fleetAutoScaler, and returns the corresponding fleetAutoScaler object, and an error if there is any.
func (c *FakeFleetAutoScalers) Get(name string, options v1.GetOptions) (result *v1alpha1.FleetAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fleetautoscalersResource, c.ns, name), &v1alpha1.FleetAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FleetAutoScaler), err
}

// List takes label and field selectors, and returns the list of FleetAutoScalers that match those selectors.
func (c *FakeFleetAutoScalers) List(opts v1.ListOptions) (result *v1alpha1.FleetAutoScalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fleetautoscalersResource, fleetautoscalersKind, c.ns, opts), &v1alpha1.FleetAutoScalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FleetAutoScalerList{}
	for _, item := range obj.(*v1alpha1.FleetAutoScalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fleetAutoScalers.
func (c *FakeFleetAutoScalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fleetautoscalersResource, c.ns, opts))

}

// Create takes the representation of a fleetAutoScaler and creates it.  Returns the server's representation of the fleetAutoScaler, and an error, if there is any.
func (c *FakeFleetAutoScalers) Create(fleetAutoScaler *v1alpha1.FleetAutoScaler) (result *v1alpha1.FleetAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fleetautoscalersResource, c.ns, fleetAutoScaler), &v1alpha1.FleetAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FleetAutoScaler), err
}

// Update takes the representation of a fleetAutoScaler and updates it. Returns the server's representation of the fleetAutoScaler, and an error, if there is any.
func (c *FakeFleetAutoScalers) Update(fleetAutoScaler *v1alpha1.FleetAutoScaler) (result *v1alpha1.FleetAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fleetautoscalersResource, c.ns, fleetAutoScaler), &v1alpha1.FleetAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FleetAutoScaler), err
}

// Delete takes name of the fleetAutoScaler and deletes it. Returns an error if one occurs.
func (c *FakeFleetAutoScalers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fleetautoscalersResource, c.ns, name), &v1alpha1.FleetAutoScaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFleetAutoScalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fleetautoscalersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FleetAutoScalerList{})
	return err
}

// Patch applies the patch and returns the patched fleetAutoScaler.
func (c *FakeFleetAutoScalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FleetAutoScaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fleetautoscalersResource, c.ns, name, data, subresources...), &v1alpha1.FleetAutoScaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FleetAutoScaler), err
}
