// Copyright 2018 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "agones.dev/agones/pkg/apis/stable/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FleetAutoScalerLister helps list FleetAutoScalers.
type FleetAutoScalerLister interface {
	// List lists all FleetAutoScalers in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.FleetAutoScaler, err error)
	// FleetAutoScalers returns an object that can list and get FleetAutoScalers.
	FleetAutoScalers(namespace string) FleetAutoScalerNamespaceLister
	FleetAutoScalerListerExpansion
}

// fleetAutoScalerLister implements the FleetAutoScalerLister interface.
type fleetAutoScalerLister struct {
	indexer cache.Indexer
}

// NewFleetAutoScalerLister returns a new FleetAutoScalerLister.
func NewFleetAutoScalerLister(indexer cache.Indexer) FleetAutoScalerLister {
	return &fleetAutoScalerLister{indexer: indexer}
}

// List lists all FleetAutoScalers in the indexer.
func (s *fleetAutoScalerLister) List(selector labels.Selector) (ret []*v1alpha1.FleetAutoScaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FleetAutoScaler))
	})
	return ret, err
}

// FleetAutoScalers returns an object that can list and get FleetAutoScalers.
func (s *fleetAutoScalerLister) FleetAutoScalers(namespace string) FleetAutoScalerNamespaceLister {
	return fleetAutoScalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FleetAutoScalerNamespaceLister helps list and get FleetAutoScalers.
type FleetAutoScalerNamespaceLister interface {
	// List lists all FleetAutoScalers in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.FleetAutoScaler, err error)
	// Get retrieves the FleetAutoScaler from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.FleetAutoScaler, error)
	FleetAutoScalerNamespaceListerExpansion
}

// fleetAutoScalerNamespaceLister implements the FleetAutoScalerNamespaceLister
// interface.
type fleetAutoScalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FleetAutoScalers in the indexer for a given namespace.
func (s fleetAutoScalerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FleetAutoScaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FleetAutoScaler))
	})
	return ret, err
}

// Get retrieves the FleetAutoScaler from the indexer for a given namespace and name.
func (s fleetAutoScalerNamespaceLister) Get(name string) (*v1alpha1.FleetAutoScaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("fleetautoscaler"), name)
	}
	return obj.(*v1alpha1.FleetAutoScaler), nil
}
