// Copyright 2018 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "agones.dev/agones/pkg/apis/stable/v1alpha1"
	scheme "agones.dev/agones/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FleetAutoScalersGetter has a method to return a FleetAutoScalerInterface.
// A group's client should implement this interface.
type FleetAutoScalersGetter interface {
	FleetAutoScalers(namespace string) FleetAutoScalerInterface
}

// FleetAutoScalerInterface has methods to work with FleetAutoScaler resources.
type FleetAutoScalerInterface interface {
	Create(*v1alpha1.FleetAutoScaler) (*v1alpha1.FleetAutoScaler, error)
	Update(*v1alpha1.FleetAutoScaler) (*v1alpha1.FleetAutoScaler, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FleetAutoScaler, error)
	List(opts v1.ListOptions) (*v1alpha1.FleetAutoScalerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FleetAutoScaler, err error)
	FleetAutoScalerExpansion
}

// fleetAutoScalers implements FleetAutoScalerInterface
type fleetAutoScalers struct {
	client rest.Interface
	ns     string
}

// newFleetAutoScalers returns a FleetAutoScalers
func newFleetAutoScalers(c *StableV1alpha1Client, namespace string) *fleetAutoScalers {
	return &fleetAutoScalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fleetAutoScaler, and returns the corresponding fleetAutoScaler object, and an error if there is any.
func (c *fleetAutoScalers) Get(name string, options v1.GetOptions) (result *v1alpha1.FleetAutoScaler, err error) {
	result = &v1alpha1.FleetAutoScaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FleetAutoScalers that match those selectors.
func (c *fleetAutoScalers) List(opts v1.ListOptions) (result *v1alpha1.FleetAutoScalerList, err error) {
	result = &v1alpha1.FleetAutoScalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fleetAutoScalers.
func (c *fleetAutoScalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a fleetAutoScaler and creates it.  Returns the server's representation of the fleetAutoScaler, and an error, if there is any.
func (c *fleetAutoScalers) Create(fleetAutoScaler *v1alpha1.FleetAutoScaler) (result *v1alpha1.FleetAutoScaler, err error) {
	result = &v1alpha1.FleetAutoScaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		Body(fleetAutoScaler).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fleetAutoScaler and updates it. Returns the server's representation of the fleetAutoScaler, and an error, if there is any.
func (c *fleetAutoScalers) Update(fleetAutoScaler *v1alpha1.FleetAutoScaler) (result *v1alpha1.FleetAutoScaler, err error) {
	result = &v1alpha1.FleetAutoScaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		Name(fleetAutoScaler.Name).
		Body(fleetAutoScaler).
		Do().
		Into(result)
	return
}

// Delete takes name of the fleetAutoScaler and deletes it. Returns an error if one occurs.
func (c *fleetAutoScalers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fleetAutoScalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fleetautoscalers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fleetAutoScaler.
func (c *fleetAutoScalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FleetAutoScaler, err error) {
	result = &v1alpha1.FleetAutoScaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fleetautoscalers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
